language: python
python:
  - "2.6"
  - "2.7"

env:
  - DJANGO_VERSION=1.5

install:
  - pip install -q django==$DJANGO_VERSION coverage pep8
  - python setup.py -q install

script: python setup.py test
